# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(800, 600)
		MainWindow.setMinimumSize(QtCore.QSize(600, 300))
		MainWindow.setBaseSize(QtCore.QSize(1920, 1080))
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
		self.gridLayout_2.setObjectName("gridLayout_2")
		self.downloadButton = QtWidgets.QPushButton(self.centralwidget)
		self.downloadButton.setObjectName("downloadButton")
		self.gridLayout_2.addWidget(self.downloadButton, 6, 0, 1, 1)
		self.log = QtWidgets.QTextBrowser(self.centralwidget)
		self.log.setObjectName("log")
		self.gridLayout_2.addWidget(self.log, 5, 0, 1, 1)
		self.gridLayout = QtWidgets.QGridLayout()
		self.gridLayout.setObjectName("gridLayout")
		self.horizontalLayout = QtWidgets.QHBoxLayout()
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.destinationLabel = QtWidgets.QLabel(self.centralwidget)
		self.destinationLabel.setObjectName("destinationLabel")
		self.horizontalLayout.addWidget(self.destinationLabel)
		self.destinationButton = QtWidgets.QPushButton(self.centralwidget)
		self.destinationButton.setObjectName("destinationButton")
		self.horizontalLayout.addWidget(self.destinationButton)
		self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
		self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
		self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.urlLineEdit = QtWidgets.QLineEdit(self.centralwidget)
		self.urlLineEdit.setMinimumSize(QtCore.QSize(686, 31))
		self.urlLineEdit.setObjectName("urlLineEdit")
		self.horizontalLayout_2.addWidget(self.urlLineEdit)
		self.urlButton = QtWidgets.QPushButton(self.centralwidget)
		self.urlButton.setObjectName("urlButton")
		self.horizontalLayout_2.addWidget(self.urlButton)
		self.gridLayout_2.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
		self.cleanButton = QtWidgets.QPushButton(self.centralwidget)
		self.cleanButton.setObjectName("cleanButton")
		self.gridLayout_2.addWidget(self.cleanButton, 7, 0, 1, 1)
		MainWindow.setCentralWidget(self.centralwidget)
		self.menubar = QtWidgets.QMenuBar(MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
		self.menubar.setBaseSize(QtCore.QSize(0, 20))
		self.menubar.setObjectName("menubar")
		self.menuFile = QtWidgets.QMenu(self.menubar)
		font = QtGui.QFont()
		font.setFamily("DejaVu Sans")
		font.setPointSize(12)
		self.menuFile.setFont(font)
		self.menuFile.setObjectName("menuFile")
		MainWindow.setMenuBar(self.menubar)
		self.statusbar = QtWidgets.QStatusBar(MainWindow)
		self.statusbar.setObjectName("statusbar")
		MainWindow.setStatusBar(self.statusbar)
		self.actionQuit = QtWidgets.QAction(MainWindow)
		self.actionQuit.setEnabled(True)
		self.actionQuit.setObjectName("actionQuit")
		self.actionDownload = QtWidgets.QAction(MainWindow)
		self.actionDownload.setObjectName("actionDownload")
		self.actionClean = QtWidgets.QAction(MainWindow)
		self.actionClean.setObjectName("actionClean")
		self.menuFile.addAction(self.actionQuit)
		self.menuFile.addAction(self.actionDownload)
		self.menuFile.addAction(self.actionClean)
		self.menubar.addAction(self.menuFile.menuAction())

		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
		self.downloadButton.setText(_translate("MainWindow", "Download"))
		self.destinationLabel.setText(_translate("MainWindow", "TextLabel"))
		self.destinationButton.setText(_translate("MainWindow", "Select Destination"))
		self.urlButton.setText(_translate("MainWindow", "add URL"))
		self.cleanButton.setText(_translate("MainWindow", "Clean"))
		self.menuFile.setTitle(_translate("MainWindow", "Actions"))
		self.actionQuit.setText(_translate("MainWindow", "Quit"))
		self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
		self.actionDownload.setText(_translate("MainWindow", "Download"))
		self.actionDownload.setShortcut(_translate("MainWindow", "Ctrl+D"))
		self.actionClean.setText(_translate("MainWindow", "Clean"))
		self.actionClean.setShortcut(_translate("MainWindow", "Ctrl+C"))
